name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.3 # Dart SDK version
  flutter: ^3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Gill
      fonts:
        - asset: assets/fonts/GillSansC.ttf
  
  uses-material-design: true
